### ISSUE TITLE
Fix errors related to Keyboard shortcut logic

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d7#1003]
```
Notice: Undefined variable: enabled_roles in keyboard_shortcut_init() (line 120 of docroot/sites/all/modules/contrib/keyboard_shortcut/keyboard_shortcut.module).
```

Should check if `$enabled_roles` is set before running `keyboard_shortcut_check_access()` on the value.

**Comment by jimafisk** [comment]
Additional context: To fix we should roll another patch on this thread: https://www.drupal.org/project/keyboard_shortcut/issues/2839535. Then just update the reference in `make.yml` so the site builds with the new patch.

**Comment by BrutiAnteneh** [comment]
### Steps involved:
1. Edit the contributed module
2. Create a patch file from a git diff
3. Upload to the issue on drupal.org
4. Update make.yml to pull in the new patch.

**Comment by reillyzlab** [comment]
Reilly will look into how/if this should migrate.

**Comment by davidrkupton** [comment]
Will patch in Drupal.org and current boston.gov-d7 as part of php7.1 evaluation.
