### ISSUE TITLE
Determine/fix what is happening with Hub user migration/purge

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d7#1050]

**Comment by jimafisk** [comment]
Context for our devs: We have a JSON feed (Reilly or I can point you to this) that we fetch from to sync user accounts and profiles using custom migrations run on cron (acquia scheduled jobs). By default Drupal migrations only add, they don't delete (see: https://www.drupal.org/project/migrate/issues/1416672)

We added a custom module `docroot/sites/all/modules/custom/hub_migrate_purge` that adds a drush command (`drush migrate-orphans-purge User`) that we setup on a scheduled job to remove users who are no longer present in the feed. However, periodically large numbers of active users were being remove from hub. The working theory is that access to the feed was interrupted and the purge command deletes all users it can't find in the feed.

**Comment by BrutiAnteneh** [comment]
@jimafisk, need testing steps for this one - thanks!

**Comment by jimafisk** [comment]
hey @BrutiAnteneh this is something that we'll need to do together.

Drupal dev testing steps:
- Backup the database in Acquia Cloud
- Manually run the migration purge via drush

QA testing steps:
- Identify a list of users who have been removed from HCM recently
- Double check that these users no longer appear in the HCM feed
- Check to make sure these users have active accounts in Drupal before the migration purge is run
- Check again to make sure these users are disabled after the purge is run
