### ISSUE TITLE
Apple Touch icons causing 404 errors in our server logs 

### ISSUE THREAD

**Issue by BrutiAnteneh** [CityOfBoston/boston.gov-d7#1069]
#### Expected Behavior/Acceptance Criteria 
<br>

Our highest frequency 404 errors are iOS based favicons, or /apple-touch-icons.
The desired outcome is to prevent these from appearing in our server logs going forward.

![4-17-2018 400 errors - filtered - _apple-touch-icon-](https://user-images.githubusercontent.com/33470951/40244926-2ee423de-5a92-11e8-9fb8-079eeded61a2.png)

**Suggested solution** from Acquia TAM Team: 

_You could consider deploying true Apple Touch icons if you have them._

**View original Acquia TAM Team support ticket:**

https://insight.acquia.com/support/requests/663402#comment-398620981174

**View the relevant server log:**

[boston-400-500-errors-20180417.csv.xlsx](https://github.com/CityOfBoston/boston.gov/files/2017603/boston-400-500-errors-20180417.csv.xlsx)

**Read more about apple touch icons:**

- [Everything you always wanted to know about touch icons
](https://mathiasbynens.be/notes/touch-icons)

- [Apple touch icon: The Good, the Bad and the Ugly](https://realfavicongenerator.net/blog/apple-touch-icon-the-good-the-bad-the-ugly/)

#### Actual Behavior
<br>
n/a

#### Browser
<br> 
n/a

#### Device
<br> 
n/a

#### Example URL
<br> 

see above

#### Relevant Screenshot(s) or Logs
<br> 

see above

#### Steps to Reproduce the Behavior/How to Test
<br> 

If we fix the issue, the 404s will also resolve.

_Reminder: Add any relevant Labels, Projects, and/or Milestone(s). If fields don't apply, please right N/A._

**Comment by reillyzlab** [comment]
If easy to implement, then implement. If not, then close.

**Comment by davidrkupton** [comment]
![192 x 192](https://user-images.githubusercontent.com/4700050/41861681-ec9709f0-786f-11e8-8b79-1ef5faabdb29.png)
image to use - place in `html.tpl.php` and store image in docroot folder.

**Comment by BrutiAnteneh** [comment]
@davidrkupton: 
Note for deploying to Production: Files need to be **_manually_** added to the sites/default/files/ folder in order to prevent them from appearing as broken links on every page.

**Comment by BrutiAnteneh** [comment]
This is all set.
