### ISSUE TITLE
Drupal component for commission list / search

### ISSUE THREAD

**Issue by finneganh** [CityOfBoston/boston.gov-d7#1103]
Need a search page that lists all boards and commissions and allows searching, filtering by category and whether or not their are open seats.

Design should be based on existing [search page on Boston.gov](https://www.boston.gov/search?utf8=%E2%9C%93&query=parks).

**Comment by finneganh** [comment]
See [product requirements](https://docs.google.com/document/d/1M313Oksc8JRYUbT7c-sUU8zsGpPMbcwIpcJ7lK6Z_Sc/edit)

**Comment by finneganh** [comment]
Example [GraphQL queries in Drupal](https://github.com/CityOfBoston/boston.gov/blob/develop/docroot/sites/all/modules/features/bos_components_commissions/bos_components_commissions.module).

Boards and Commissions [GraphiQL interface](https://apps.boston.gov/commissions/graphiql) for testing queries.

**Comment by reillyzlab** [comment]
Only content so closed
