### ISSUE TITLE
Add ability to upload documents to Transactions Grid component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d7#1129]
#### Expected Behavior/Acceptance Criteria 
<br>
Add the ability for a content author or editor to add documents to a Transaction Grid component on Boston.gov.

#### Actual Behavior
<br>
Right now, the only options are to add external and internal links.

#### Browser
<br> 
All browsers

#### Device
<br> 
All devices

#### Example URL
<br> 
The [Parking Clerk's Office](https://www.boston.gov/departments/parking-clerk) has a Transactions Grid component that you can test.

#### Relevant Screenshot(s) or Logs
<br> 

Looks like this:
![image](https://user-images.githubusercontent.com/7929556/41785162-b4786de6-760f-11e8-846b-11c7d5ff9ab7.png)

<br>
Would like to have three options, similar to this:

![image](https://user-images.githubusercontent.com/7929556/41785206-dcb07542-760f-11e8-838d-0bf850e0d51b.png)

#### Steps to Reproduce the Behavior/How to Test
<br> 

1. Go to a page with a Transactions Grid component on it. For example, boston.gov/parking
2. Add another item to the Transactions Grid at the top of the components section.
3. You'll see options are only for "external" and "internal" links.

_Reminder: Add any relevant Labels, Projects, and/or Milestone(s). If fields don't apply, please right N/A._

**Comment by BrutiAnteneh** [comment]
The issue passed as expected:

![image](https://user-images.githubusercontent.com/33470951/43344533-161475fe-91b8-11e8-96da-cfd35da662db.png)
