### ISSUE TITLE
Missing "news_announcements - other" list from News & Announcements component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d7#1153]
#### Expected Behavior/Acceptance Criteria 
<br>
A user should be able to select the "news_announcements - other" list from a News & Announcements component. This would allow a user to tag a post to make it show up on article pages on Boston.gov.

#### Actual Behavior
<br>
The "news_announcements - other" list appears to be missing from the News & Announcements component. Users are unable to tag a post to make it show up on an article page.

#### Browser
<br> 
All browsers

#### Device
<br> 
All devices

#### Example URL
<br> 
The [Martin's Park project page](https://www.boston.gov/departments/parks-and-recreation/martins-park) is an example of a location where I'd like to use a News & Announcements component on an article page.

#### Relevant Screenshot(s) or Logs
<br> 
You can see the missing list item in this screenshot:
![news-announcements](https://user-images.githubusercontent.com/7929556/43147052-1e8c4ef8-8f30-11e8-822a-5dd29b51b9a8.jpg)
<br><br>
In the Upcoming Events component, you can see that this component, which also relies on related content, features an "other" list:
![upcoming-events](https://user-images.githubusercontent.com/7929556/43147101-37c4e5c4-8f30-11e8-8e53-50a58e4598aa.jpg)

#### Steps to Reproduce the Behavior/How to Test
<br> 

1. Go to the [Martin's Park page](https://www.boston.gov/departments/parks-and-recreation/martins-park)
2. Add a News & Announcements component
3. Try to add the "news_announcements - other" list to the page. You should see it missing.

_Reminder: Add any relevant Labels, Projects, and/or Milestone(s). If fields don't apply, please right N/A._

**Comment by jimafisk** [comment]
@duffy-james there's a chance this was updated to be called "Most Recent" instead of other:

![most_recent](https://user-images.githubusercontent.com/5913244/43166357-60067f8c-8f64-11e8-9376-6fe0c5ee91d9.png)

Any chance this is the same option you're looking for?

**Comment by duffy-james** [comment]
@jimafisk thanks Jim. It actually wasn't "most recent", it was the "news" list. As a suggestion, I wonder if we could change the name of the list to "articles" instead of "news" to make it more obvious.

Thanks for looking into this!

**Comment by jimafisk** [comment]
I spoke w @duffy-james and the issue is actually with the item below the link circled in red above. The option is called `news_announcements - News` but should be labeled `news_announcements - Articles`

**Comment by jimafisk** [comment]
@duffy-james in digging into this more, this View (/admin/structure/views/view/news_announcements/edit/news_events) is creating a relationship to the `field_related_content` field. This field uses the following bundles:
- Article
- How-To
- Landing Page
- Script Page
- Tabbed Content

That's likely why it used to be reference to as "Other". I agree that "News" does not seem the appropriate label here, do you think that "Article" still works better than "Other"? I just wanted to double check since it encompasses multiple content types.
