### ISSUE TITLE
Metrolist's Lotteries and Resale - needs to be fixed Updated

### ISSUE THREAD

**Issue by shanaberry13** [CityOfBoston/boston.gov-d7#1157]
#### Expected Behavior/Acceptance Criteria 
<br>
Neighborhood should show on listings within the City of Boston.
#### Actual Behavior
<br>
On Metrolist's Lotteries and Resales page, it does not state Boston or the neighborhood of Boston under 'Property Address' for developments with affordable housing in Boston. However, for developments outside of Boston, it does list the city or town the development is in. 

Would like to include Boston or the Boston neighborhood to the 'Property Address' section for developments in Boston. 

Lotteries and Resale page: https://www.boston.gov/metrolist/lottery-and-resale?order=field_mah_lottery_type&sort=asc 

Examples: 39 A Street, The Boulevard, Walker Park Apartments
#### Browser
<br> 

#### Device
<br> 

#### Example URL
<br> 

#### Relevant Screenshot(s) or Logs
<br> 

#### Steps to Reproduce the Behavior/How to Test
<br> 

_Reminder: Add any relevant Labels, Projects, and/or Milestone(s). If fields don't apply, please right N/A._

**Comment by reillyzlab** [comment]
@shanaberry13 we'll look into this next week (week of 8/6/18)

**Comment by shanaberry13** [comment]
Amazing! Thank you, Reilly! 😊



*Shana Berry, CSM, CSPO, SCA*
Business Analyst and Product Owner of Information & Technology
Department of Neighborhood Development (DND)
City of Boston| 26 Court Street| Boston, MA 02108
*Office:* 617.635.0288

**Comment by jimafisk** [comment]
Hey @shanaberry13 I started looking into this issue a little early (just couldn't help myself). It looks like the Neighborhood information from Salesforce is not making it over to Drupal for lottery posts. Basically the display you referenced has logic that says, if there is a Neighborhood listed, display it, but if there is no neighborhood lists, try to display the "Outer Neighborhood" value if it exists. 

Could we take a look together sometime next week? Thanks!

**Comment by shanaberry13** [comment]
Hi Jim,

Great! Thank you so much for looking into this. I think I may know why it
isn't showing up. I do have time next week to get together about this.
Please let me know dates and times you are available.

Thanks,



*Shana Berry, CSM, CSPO, SCA*
Business Analyst and Product Owner of Information & Technology
Department of Neighborhood Development (DND)
City of Boston| 26 Court Street| Boston, MA 02108
*Office:* 617.635.0288

**Comment by jimafisk** [comment]
Need to change to `Neighborhood_pl__c` `Neighborhood__c` on field mapping.
