### ISSUE TITLE
Search bar cut off on search results page

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d7#1182]
#### Expected Behavior/Acceptance Criteria 
On the search results page, the search input is usually underneath the site's header so the user can see what they've searched for and start another search if necessary.

#### Actual Behavior
The search bar is getting cut off, so users can't see what they've input and have to click on the search icon in the header to start another search.

#### Browser
Chrome 68
Firefox 62

#### Device
Desktop

#### Example URL
https://www.boston.gov/search?utf8=%E2%9C%93&query=test

#### Relevant Screenshot(s) or Logs
![image](https://user-images.githubusercontent.com/12868231/45649570-b12bcb00-ba99-11e8-9c18-bd698b2241c4.png)

#### Steps to Reproduce the Behavior/How to Test
Search for a term on boston.gov and check if the search input can be seen on the results page.

**Comment by jimafisk** [comment]
Looks like we could just add a `nm` class to the `#page` div, see the example from the homepage:

![mn-class](https://user-images.githubusercontent.com/5913244/46161163-c56a8780-c252-11e8-87b8-d430a0959c97.png)

This is missing on the search page:

![no_nm-class](https://user-images.githubusercontent.com/5913244/46161167-c996a500-c252-11e8-9742-703b3c186fd5.png)
