### ISSUE TITLE
Emergency alert sign up widget issue - forcing email input

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d7#1218]
On the emergency alert sign up we give the option of signing up for email **or** phone.

When folks put in only a phone number they are forced (required) to also enter an email. 

We should remove this requirement so that they are only forced to enter a phone number.

Example of component can be found here: https://www.boston.gov/emergency-alerts

**Comment by davidrkupton** [comment]
[DU] Added Matt in.
