### ISSUE TITLE
Broken Linkit Module

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d7#1220]
#### Expected Behavior/Acceptance Criteria 
When clicking the LinkIt button in a WYSIWYG text field, you should see two simple fields that allow you to search the site for existing content:

![working_linkit](https://user-images.githubusercontent.com/5913244/48599040-f3f00f00-e933-11e8-8ba1-4653f22ec2f1.png)

#### Actual Behavior
<img width="1335" alt="screen shot 2018-11-15 at 4 25 52 pm" src="https://user-images.githubusercontent.com/5913244/48598912-5dbbe900-e933-11e8-93ef-d9774e475f7d.png">

Summary:
1. Linkit isn't displaying as intended
2. Nothing populates when text is entered in both fields,
3. Unable to cancel out of the dialogue box.
4. Clicking insert link takes user here:

<img width="1396" alt="screen shot 2018-11-15 at 5 04 33 pm" src="https://user-images.githubusercontent.com/5913244/48598910-598fcb80-e933-11e8-9330-ac30a23ec672.png">

It has been reported that this is happening on production for all users / roles.

**Comment by jimafisk** [comment]
Tested with `admin`, `content_admin`, and Bruti's CON ID. It seems to be working on my end.

@BrutiAnteneh can you try again with an incognito / private browsing window to make sure this isn't a caching issue? If you're still seeing the issue on your end, can you please add browser and device details here. Thanks!

**Comment by BrutiAnteneh** [comment]
@jimafisk and @davidrkupton  
The problem persists in incognito/private browser.

It's looking like this may be related to Content type.

I added a Content Editor Test component to our regression pages ([Program Initiative Test Page](https://www.boston.gov/innovation-and-technology/program-initiative-profile-test-page#content-editor-test) and [Article Test page](https://edit.boston.gov/departments/digital-team/test-page#content-editor-test)) to test WYSIWYG functions:

- [ ] LinkIt module

- [ ] Media Browser
 
I was able to reproduce the bug when testing on the **Article** test page: 

**URL:** https://www.boston.gov/departments/digital-team/test-page#content-editor-test

![image](https://user-images.githubusercontent.com/33470951/48646367-aff21e00-e9b6-11e8-8c7d-a1862d7080c0.png)


Alternatively, I am able to insert a link using the Linkit module on a **Program** page:

**URL:** https://www.boston.gov/innovation-and-technology/program-initiative-profile-test-page#content-editor-test

![image](https://user-images.githubusercontent.com/33470951/48646407-c4ceb180-e9b6-11e8-8bca-15bbe6d82692.png)

**Comment by jimafisk** [comment]
Thanks for the additional information! Based on further testing, this issue appears to happen only on certain existing pages: `/node/17356/edit` (the digital-team testing page)

It does not occur for new pages `/node/add/article`. 

It also does not appear to occur on any other article pages based on a random sampling I took: `/node/3921/edit`, `/node/2161/edit`, `/node/7236/edit`, `/node/52701/edit`, `/node/34266/edit`, `/node/2956/edit`, `/node/48056/edit`

@BrutiAnteneh is this issue isolated to only the "test" page? If there are other examples you've seen, can you send them my way so I can try to identify what is common between them? Thanks!

**Comment by BrutiAnteneh** [comment]
@jimafisk, based on your findings, I created a new article page to A/B test against the original, all-components Test Page. I can confirm that LinkIt appears to be broken only in that component Test Page: 

### ARTICLE PAGE - TEST WYSIWYG
url: https://www.boston.gov/article-page-test-wysiwyg
![image](https://user-images.githubusercontent.com/33470951/49762258-3dafe900-fc97-11e8-9cbe-9ad168a01b2a.png)

### TEST PAGE
**Url:** https://www.boston.gov/departments/digital-team/test-page
![image](https://user-images.githubusercontent.com/33470951/49762736-a3e93b80-fc98-11e8-98e4-ef251e7bd564.png)
