### ISSUE TITLE
Can't edit the Transactions Grid component on the Environment Department page

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d7#1229]
#### Expected Behavior/Acceptance Criteria 
Content Authors should be able to add new `internal_link`s.

#### Actual Behavior
On the edit screen we are receiving the following error: `You are not allowed to add any of the bundles.`

#### Example URL
https://www.boston.gov/departments/environment

#### Relevant Screenshot(s) or Logs

![image](https://user-images.githubusercontent.com/5913244/50692465-f56bb880-1001-11e9-8948-00fc558995db.png)

**Comment by jimafisk** [comment]
I have a strong suspicion that this is related to field_collections given that is appearing on the transactions grid and group of links - grid components per #510 . The issue does not appear to be related to the paragraph permissions update that fixed the AJAX error on #672 . 

Related: https://www.drupal.org/project/paragraphs/issues/2562875

**Comment by jimafisk** [comment]
This does not appear to be isolated to field collections. It was flagged on a `group-of-links-mini-grid` components which do not use field collections (url: `/node/7536/edit`):

![image 1](https://user-images.githubusercontent.com/5913244/50701933-5654ba00-101d-11e9-8d2f-e471bdc13329.png)

**Comment by jimafisk** [comment]
@duffy-james the quick hack around this issue seems to be publishing the current draft and re-editing. That should free up these components. Still working on a longer term fix. Thanks!

**Comment by reillyzlab** [comment]
Closing since we will resolve on Drupal 8
