### ISSUE TITLE
Make BCYF Applications reusable

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d7#1233]
#### Expected Behavior/Acceptance Criteria 
The ability to reuse certain component (Drupal paragraph) content across [BCYF community center pages](https://www.boston.gov/community-centers). Possibly substitute these components for entity references (with the help of [inline entity form](https://www.drupal.org/project/inline_entity_form)) and create a content type specific to the sections outlined below.

#### Actual Behavior
We have a variety of [BCYF community center pages](https://www.boston.gov/community-centers), for example:
- https://www.boston.gov/departments/boston-centers-youth-families/bcyf-blackstone
- https://www.boston.gov/departments/boston-centers-youth-families/bcyf-charlestown
- https://www.boston.gov/departments/boston-centers-youth-families/bcyf-clougherty-pool

These pages all have the following two components (among others):
- Three Column Text (`/admin/structure/paragraphs/text-three-column/fields`) for "Membership Rates". 
- Group of Links - Mini Grid (`https://0.0.0.0/admin/structure/paragraphs/group-of-links-mini-grid/fields`) for "More Resources"

There is no way to reference content that has already been created on other pages.

#### Browser
All

#### Device
All 

#### Example URL
(see "Actual Behavior" section)

#### Relevant Screenshot(s) or Logs
Text component with application information:

![image](https://user-images.githubusercontent.com/5913244/50923461-0742c680-141b-11e9-9bae-d6a8d0fe3c9f.png)

Mini grid with links:

![image 1](https://user-images.githubusercontent.com/5913244/50923463-0ad64d80-141b-11e9-8fe1-2c88f6cc43c9.png)

**Comment by jimafisk** [comment]
@duffy-james in looking through the "Membership Rates" sections, it looks like these values are different across all pages. If you browse through the first values on the first few pages, you'll see:
- https://www.boston.gov/departments/boston-centers-youth-families/bcyf-charlestown Adult: $40
- https://www.boston.gov/departments/boston-centers-youth-families/bcyf-blackstone Adult: $30
- https://www.boston.gov/departments/boston-centers-youth-families/bcyf-condon Adult: $25
- https://www.boston.gov/departments/boston-centers-youth-families/bcyf-curley Adult: $100

I'm having trouble conceptualizing how we'd abstract this to cut down on editing. Is it the structure itself (e.g. Adult, Teen, Youth, Senior categories) that would be nice to template across pages? We could do something like that by creating a custom component much the same way we've done all the other components, but my worry with doing that is it makes things more rigid and would actually probably increase the amount of time it takes to apply edits to these sections. It also doesn't account for variations I'm noticing by looking through the first couple of pages (e.g. [Curly](https://www.boston.gov/departments/boston-centers-youth-families/bcyf-curley) has a membership category called "Adult Aerobic Membership" that does not appear on other pages. Any insight you have would be appreciated!

Regarding the "More Resources" section, I assume the desire is to have a list of links that we can pull from? Currently most of the pages use different links, but I do see some that appear across several pages, for example the [Community Center Map](http://boston.maps.arcgis.com/apps/MapTour/index.html?appid=e49b95556b224717b25236532303e41b) link. Are these links changing often?

**Comment by duffy-james** [comment]
@jimafisk I didn't realize the information in these applications sections wasn't consistent. I agree it doesn't make sense to have one component for them all.

The "more resources" section would be more consistent. This section is typically for generalized links related to BCYF. I could see a use case for creating a "group of links - mini grid" component/paragraph, but let me check in with Dawn from BCYF and get back to you.

**Comment by duffy-james** [comment]
@jimafisk update on this. Had an email with Dawn at BCYF and she clarified what they were hoping to have for the duplicated component. Ideally it would mirror a drawers component, where a user could add additional drawers as they go:
![image](https://user-images.githubusercontent.com/7929556/50989915-aaa8df80-14de-11e9-93d6-c3341fe48a35.png)

Inside of these drawers would be the option to add one, two, or three column layout text fields, as we have now with our current drawers component. They're working to consolidate pricing for memberships, so that's a drawer that they would potentially add later.

The drawers component makes sense to me because it gives the user flexibility around adding a lot without it taking up much space, but let me know what you think Jim.

**Comment by reillyzlab** [comment]
Won't do this in D7 - too big of feature at this point
