### ISSUE TITLE
Adjustments to procurement ads content type

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d7#1235]
Work in progress 

# Bug fixes needed
- [x] Awarding authority and related links title and title/url (related links item also found under sidebar but isn't working) are all sitting above the rest of the CMS and broken from working

![screen shot 2019-01-10 at 3 08 29 pm](https://user-images.githubusercontent.com/20731897/50994198-a2a26d00-14e9-11e9-8b18-310bfee3d1f3.png)

# Feature Adjustments Needed:

## Under 'Basic Information'
- [ ] Procurement footer: Shouldn’t be a drop down field. It should be content that’s automatically added to every procurement advertisement as the last paragraph of the body copy. Procurement office has said they were going to provide language, but has yet to do so, so please use this language for now:

> The City of Boston is committed to and affirmatively ensures that Disadvantaged Business Enterprises (DBE), Small Local Business Enterprise (SLBE), Minority Business Enterprise (MBE), Women Business Enterprise (WBE), and Veteran Owned Small Business Enterprise (VOSBE) firms shall be afforded full opportunity to submit qualifications in response to this and will not be discriminated against on the basis of race, color, national origin, ancestry, disability, gender, transgender status, political affiliation, age, sexual orientation, or religion in any consideration leading to the award of contract. No qualified disabled person shall, on the basis of disability, be excluded from participating in, be denied the benefits of, or otherwise subjected to discrimination in any consideration leading to the award of contract. The award of any contract shall be subject to the approval of the Mayor of Boston. The maximum time for IFB acceptance by the City after the opening of the bids shall be ninety (90) days unless noted otherwise. The maximum time for RFP acceptance by the City after the opening of the bids shall be one hundred-eighty (180) days unless noted otherwise. The City/County and the Official reserve the right to reject any or all bids, or any item or items thereof, and to award a contract as the Official deems to be in the best interest of the City. All contracts shall be subject to the availability of an appropriation therefore, if sufficient funds are not appropriated for the contract in any fiscal year, the Official shall cancel the contract. The City reserves the right to reject any and all bids, or any part or parts thereof, and to award a contract as the Official deems to be in the best interest of the City. This contract shall be subject to the availability of an appropriation. If sufficient funds are not appropriated for the contract in any fiscal year, the Official shall cancel the contract. Late bids will not be accepted. 

- [ ] Remove Procurement footer taxonomy item
- [x] Massachusetts General Law: User should be able to select from multiple options that display text and allow a link elsewhere. > Believe original thought it that this would be a taxonomy but am open to thinking through this if helpful.
- [x] Massachusetts General Law: When Reilly tries to go into this field I get an ajax error.
- [x] Offering: Change the word from 'Supplies' to 'Goods'
- [x] Change 'Procurement' Field to be 'Procurement Type' to match taxonomy
- [x] When try to enter info into 'procurement' field Reilly gets an ajax error
- [x] When try to enter info into 'department' field Reilly gets an ajax error

Multi-year contract: double check where it shows up on the front end - didn’t for Kevin/Diana

## Under 'Sidebar'
- [ ] Change All Time Stuff to the following
    - [x] Change Title of 'Period Open' to 'Bid Date'
    - [ ] Open question to Jim: "Is it possible to que the publishing controls off of the open-close date and time in sidebar?" If so, would be helpful, but no need if large LOE.
    - [x] Add field for 'Advertisement Date' with one date and no time (if possible). Or at least only date should appear visually to front end user. This field should appear before Period Open.
- [x] When try to enter info into 'Awarded By' field Reilly gets an ajax error

## Under 'Related Items'
- [x] When try to enter info into 'Related departments' field Reilly gets an ajax error

## API
- [ ] Create an API/view of the information

## Roles
- [ ] Ensure that content editors can edit and publish this content type.

Note: There could be a few more items to adjust, but Reilly can't 100% test and save a test page, so we will most likely need to review again once the ajax errors are resolved.

**Comment by jimafisk** [comment]
@reillyzlab do you have an ad_blocker browser extension enabled by chance? See Bruti's note about AJAX errors: https://github.com/CityOfBoston/boston.gov-d7/issues/940#issuecomment-403884900 

Also just wanted to follow up with design materials for my reference:
- **PDF:** https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46ca9d9e30d8b18fbffafd0fe64de29b234324676b5ee17e2786b37fea472c54575d1bac145a5e44fea8dc2fa0e53562964e49bc8f3900299f7744eeaa880dbd01b0218e4e87b7b98d49c8ed3820e199c2.pdf
- **All design assets:** https://drive.google.com/drive/folders/14MYSCB9mpRUjU5Gl9r5F-s0nyMw31Cmo

**Comment by jimafisk** [comment]
Regarding `related_links`, it appears the section in the sidebar is working. Here is the edit screen for those links:

![related_links_edit](https://user-images.githubusercontent.com/5913244/51048248-7691f500-1598-11e9-93a5-ad22c59af97a.png)

Here's what that looks like on display:

![related_links_display](https://user-images.githubusercontent.com/5913244/51048253-785bb880-1598-11e9-9bdf-385679280f10.png)

@reillyzlab do you know if there was another purpose for the additional "related links" section at the top of the edit screen (as seen in the screenshot reported initially on this issue)? It looks like per the default text that this was supposed to get replaced programmatically, but I'm unsure what is the desired outcome. Do you happen to remember, or do you think we should remove this redundancy? Thanks!

**Comment by jimafisk** [comment]
I'm trying to think through the best way to approach the `procurement_footer` adjustments. I think the easiest and most flexible way is to use the existing structure to:

1. Create a "default" procurement footer taxonomy term (`/admin/structure/taxonomy/procurement_footer/add`)
2. Set the default value on the content type to reference this term (`/admin/structure/types/manage/procurement-advertisement/fields/field_procurement_footer`)
3. Optionally we can set field_procurement_footer to be required so users must leave it selected

The editing experience would look the same as now, except the "default" would automatically be selected:

![default_footer_edit](https://user-images.githubusercontent.com/5913244/51050960-6d0c8b00-15a0-11e9-9b3a-3ee399d2e989.png)

This is already setup to get appended to the body section on display:

![default_footer_display](https://user-images.githubusercontent.com/5913244/51050987-7f86c480-15a0-11e9-8443-3372fb12080b.png)

The advantage of this structure is that it allows editing of the text without needing a programmatic change that needs to be deployed. If we add a static text field with a default value, you could edit the text for a particular instance, but the default would need to be changed in code. Similarly, we could remove the field altogether and add the text in on the backend, but every slight adjustment would need to be made by a developer and would have the delay of the deployment process. The other advantage of the taxonomy approach is you could have multiple versions of the footer language if desired, but it's not required. 

@reillyzlab do you think steps 1 - 3 outlined above are acceptable, or would you rather a different approach? Thanks!

**Comment by jimafisk** [comment]
Regarding "Massachusetts General Law" this should already be a taxonomy called `massachusetts_general_law` found at `/admin/structure/taxonomy/massachusetts_general_law`. Currently this is a lookup field:

![mass_gen_law](https://user-images.githubusercontent.com/5913244/51052872-ff635d80-15a5-11e9-9d5c-610f33c3adb9.png)

Do you prefer this is changed to:
1. Checkboxes / select list?
2. Multi-select field (Currently you can only choose one value)?

**Comment by jimafisk** [comment]
@reillyzlab we have two similar fields:
1. Awarded By	(`field_awarded_by`): Entityreference to the "Person Profile" content type. This appears in the sidebar.
2. Awarding Authority (`field_awarding_authority`): Entityreference to the "Contact" taxonomy. This is the field at the very top of the form and does not seem to be available on display currently. 

Do you know the purpose of the field in No. 2? This is the same field you called out in the original issue. If we don't know what these are supposed to be doing, I vote to remove. Thanks!

**Comment by jimafisk** [comment]
Changing "Supplies" to "Goods" is a content change so I went ahead and updated this on production: `field_offering` is an entityreference to the `bid_offering` taxonomy (`/admin/structure/taxonomy/bid_offering`)

**Comment by jimafisk** [comment]
Here's what the new Advertisement Date looks like:

![ad_date](https://user-images.githubusercontent.com/5913244/51214820-01eaed80-18ed-11e9-8c04-e2862b3ff86a.png)

I assume this will need at least a label update. I left as "Ad Date" for now because longer titles like "Advertisement Date" overlap with the date text and would require a patterns update.

Here's the edit (note it does not require "time" values):

![ad_date_edit](https://user-images.githubusercontent.com/5913244/51214923-52fae180-18ed-11e9-9b75-12718730da80.png)

The label updates should be taken care of per https://github.com/CityOfBoston/boston.gov-d7/pull/1241

**Comment by reillyzlab** [comment]
@jimafisk this is still a bug:

# Bug fixes needed
- [ ] Awarding authority and related links title and title/url (related links item also found under sidebar but isn't working) are all sitting above the rest of the CMS and broken from working

![screen shot 2019-01-10 at 3 08 29 pm](https://user-images.githubusercontent.com/20731897/50994198-a2a26d00-14e9-11e9-8b18-310bfee3d1f3.png)

**Comment by reillyzlab** [comment]
@jimafisk listing pages for active and archive are not working. tried to add and the page displays the accurate filters, but does not display with the bids and rather says 'no public notices' found

**Comment by reillyzlab** [comment]
@jimafisk submissions UI doesn't display accurately in general and awarded submission doesn't work at all

**Comment by BrutiAnteneh** [comment]
## AJAX UPDATE
@jimafisk I can confirm cause of AJAX errors is the same as https://github.com/CityOfBoston/boston.gov-d7/issues/940#issuecomment-403884900 

I retested the fields @reillyzlab identified above https://github.com/CityOfBoston/boston.gov-d7/issues/1235#issue-397870427 with the ad blocker on and off: 

When the ad blocker was **on**, the AJAx error was triggered in each field.
When the ad blocker was **off**, the AJAX errors disappeared.

**Comment by BrutiAnteneh** [comment]
@jimafisk wondering if it's possible to make the **Related departments** field auto-fill with the department entered in the **Awarding Authority** field. If not possible, let's just remove the requirement for this field.

# Feature Adjustment
## Related Items Tab

![image](https://user-images.githubusercontent.com/33470951/54052431-64a48b00-41b2-11e9-9a58-a62e2b0243db.png)

**Comment by jimafisk** [comment]
@BrutiAnteneh can that field be removed completely? It seems to be redundant, see: https://github.com/CityOfBoston/boston.gov-d7/issues/1235#issuecomment-454559267 Thanks!

**Comment by BrutiAnteneh** [comment]
@jimafisk following up with what you said here https://github.com/CityOfBoston/boston.gov-d7/issues/1235#issuecomment-454581376.

In order to stay consistent with the procurement nomenclature (seen on the statewide [commbuys](https://www.mass.gov/files/documents/2016/10/od/finding-open-rolling-enrollment-bids-when-logged-in-commbuys.pdf) site), would it be possible to change Posted to **Bid Open** and Closes to **Bid Close**?

![image](https://user-images.githubusercontent.com/33470951/54057145-15fded80-41c0-11e9-969d-ba45a69ba841.png)

**Comment by BrutiAnteneh** [comment]
@jimafisk in reference to https://github.com/CityOfBoston/boston.gov-d7/issues/1235#issuecomment-471063645
 
**Awarding Authority** appears to be part of the procurement nomenclature. It's used frequently in the [City Record](https://www.boston.gov/sites/default/files/imce-uploads/2019-03/03042019m_city_record_wlinks.pdf) to reference the City Department associated with the advertisement, and so its intended position in the Sidebar makes sense.
 
![image](https://user-images.githubusercontent.com/33470951/54058071-c836b480-41c2-11e9-8fdc-dccf4392183a.png)

**Comment by BrutiAnteneh** [comment]
@jimafisk and @reillyzlab:

 referencing https://github.com/CityOfBoston/boston.gov-d7/issues/1235#issuecomment-454820688

> Regarding the open question: "Is it possible to queue the publishing controls off of the open-close date and time in sidebar?"

I believe @reillyzlab is referring to publishing a procurement advertisement page here 

Procurement Adverts, must be publicized a certain number of days **_before_** the Bid Open date. For example, if the Bid Open date is 2/13/2019, then the Ad Date should be 2/3/2019.  

I think Reilly might be asking if it's possible to cue the page's publish date with the `field_advertisement_date` to ensure that the advertisement is publicized for the required number of days.

![image](https://user-images.githubusercontent.com/33470951/54059942-eacbcc00-41c8-11e9-9355-ff1cf01a2e6a.png)

**Comment by BrutiAnteneh** [comment]
@jimafisk and @reillyzlab:  

in reference to @reillyzlab's mention of a link https://github.com/CityOfBoston/boston.gov-d7/issues/1235#issue-397870427:

I believe this is related to the stakeholder's request that we include an external link to Massachusetts **General Laws Chapter 30b**: https://malegislature.gov/Laws/GeneralLaws/PartI/TitleIII/Chapter30B
 
Currently, a selection from the `massachusetts_general_law` lookup field displays a plaintext citation the MGL chapter and section:

![image](https://user-images.githubusercontent.com/33470951/54062507-7008ae00-41d4-11e9-9d4c-37d1af0e48f1.png)

The same link should appear on every page, and can be programmed into the Procurement Advert content type because: 
-  Chapter 30b Lists each section of the Uniform Procurement Act (table of content style)
-  is not dependent on any of the `massachusetts_general_law` lookup field options. 

@jimafisk it's totally up to you how this is done

**Comment by jimafisk** [comment]
Spoke with @reillyzlab and @BrutiAnteneh, these are the actions items:
1) Remove "Basic Information > Departments" (replace with "Awarding Authority" which is currently above the tabs)
2) Move "Related Links" to Sidebar tab. Related links should prepopulate with:
  - Procurement Department [link to: [Boston.gov/procurement](https://boston.gov/procurement)]
  - Govdeals [link to: [www.govdeals.com](https://www.govdeals.com)]
  - Commbuys [link to: [www.commbuys.com/bso](https://www.commbuys.com/bso)]
3) Remove "Related Items" tab and child fields completely for now

**Comment by jimafisk** [comment]
@mmcgowanBOS can you remove some fields from the `procurement_advertisement` content type? 

Basically the issue is that when you remove fields from a feature, it does not actually delete the field. [This is by design](https://drupal.stackexchange.com/questions/27442/features-workflow-issue-with-deleting-a-field).

Currently if you create a new procurement advertisement there are a bunch of fields under "Related Items":
![related_fields](https://user-images.githubusercontent.com/5913244/56433865-6f1d6e80-62a0-11e9-957e-da8303b639a4.png)

Per a discussion I had with @reillyzlab and @BrutiAnteneh all these fields can be removed (including the "Related Items" field group). These fields also are not actually connected to the mechanism that makes related content work. In the future we may re-implement using the new structure.

You can remove these by implementing a new [hook_update_N()](https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_update_N/7.x) in `docroot/sites/all/modules/features/bos_content_type_procurement_advertisement/bos_content_type_procurement_advertisement.install` like we did here: https://github.com/CityOfBoston/boston.gov-d7/blob/develop/docroot/sites/all/modules/features/bos_content_type_procurement_advertisement/bos_content_type_procurement_advertisement.install#L38

Here's an example of how to delete a field group: https://github.com/CityOfBoston/boston.gov-d7/blob/enable_related/docroot/profiles/bos_profile/bos_profile.install#L1362

**Comment by mmcgowanBOS** [comment]
Hi @James Fisk <james.fisk@boston.gov> . Sure, I can take a look / crack at
it.

**Comment by BrutiAnteneh** [comment]
@reillyzlab and @mmcgowanBOS 
## ERRORS FOUND ON BOTH LISTING PAGES:

- [ ] Change text that appears when a search yields 0 results. It currently defaults to say 'No Public Notices Found'
![image](https://user-images.githubusercontent.com/33470951/56512202-aee09200-64fc-11e9-8b58-c66917a3c3c3.png)

- [ ] Ensure Department Filter opens to reveal a populated list of departments:
![image](https://user-images.githubusercontent.com/33470951/56513158-85753580-64ff-11e9-99f8-d47a302a06ba.png)

See working example on [Public Notices ](https://www.boston.gov/public-notices)listing page:
![image](https://user-images.githubusercontent.com/33470951/56513415-6c20b900-6500-11e9-8cbd-cf28c6bdab33.png)

**Comment by mmcgowanBOS** [comment]
OK. The procurement updates have been implemented and are now on stage and ready to be tested.

**Comment by mmcgowanBOS** [comment]
**Update:** As previously noted, there were a few more updates regarding the archive and regular bid listing pages. These all have been addressed (as far as I can see) and are up on stage. You'll have to create 2 new listings pages for Bid Listings and Bid Listings Archive on the stage environment, and add the proper List Component *(see below for explanation). Once done, you'll see all the updates in the views that display. 

* When deploying to stage, the DB gets overridden with Prod DB, so this is why those 2 pages have to be recreated. 

Let me know if there are any questions, etc.

**Comment by reillyzlab** [comment]
Finishing this up in Drupal 8 so closing here.
