### ISSUE TITLE
Related Content Phase 2: Option to select "all of type" 

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d7#1244]
#### Expected Behavior/Acceptance Criteria 
In speaking with @duffy-james we determined there should be options for particular groups of content, like Neighborhoods or BCYF, to select all to reduce tedious actions during content creation. 

To illustrate the general idea, you would have links or buttons like this:

![select_all_of_type](https://user-images.githubusercontent.com/5913244/51411274-48cb2400-1b35-11e9-8a93-ae8cae79d2ba.png)

Then if you clicked "All Neighborhoods" for example, it would automatically populate the fields similar to this:

![neighborhoods](https://user-images.githubusercontent.com/5913244/51411551-47e6c200-1b36-11e9-9c80-f25dd7152c74.png)

We could look at what we're currently doing with Neighborhoods under the old related content as an example. It is pulling a list of "Neighborhoods" out of the "Related places" field. So every time you add a Neighborhood via Related Places and save, it will appear as checked in the Neighborhood list. This is all queued off of a boolean called `field_place_neighborhood` that we set when creating Place Profile content:

![is_neighborhood](https://user-images.githubusercontent.com/5913244/51411757-04d91e80-1b37-11e9-9511-41bbac5ce7dd.png)

We could set up another called `field_place_bcyf`. We'd still need to update the form_alter logic to handle this.

**Comment by reillyzlab** [comment]
Closing since we're moving to Drupal 8.
