### ISSUE TITLE
Translate toggle/button disappears on mobile [portrait]

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d7#1268]
The 'translation' selection button on mobile, portrait display disappears and is not accessible on mobile. 

We need to re-implement this.

@sebastianebarb can you provide design for this

**Comment by mmcgowanBOS** [comment]
This has been updated and fixed along with the new "B" logo for mobile viewport. It was merged into Develop yesterday. It should be pushed to Prod on Thursday.

See PR here...
https://github.com/CityOfBoston/boston.gov-d7/pull/1277
