### ISSUE TITLE
Change patterns library used by Acquia pre-deploy environments 

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d7#1308]
#### Expected Behavior/Acceptance Criteria 
* Acquia's dev, ci and uat environments should be using css from the patterns staging server.
* Acquia's test(stage) and prod environments should use css from patterns.boston.gov (patterns production server)

**Comment by reillyzlab** [comment]
Closing since we're moving to Drupal 8.
