### ISSUE TITLE
Bash Week: Text breaking onto 2 lines on mobile

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d7#1317]
On specifically mobile view, all programmatically buttons with lengthier text has it's text break:

![IMG_0791](https://user-images.githubusercontent.com/20731897/55185522-e876e500-516a-11e9-91c5-f3d710d59f71.JPG)

specifically found on boston.gov/economic-center on an iphone x

unsure whether this is patterns or something with drupal specifically. 

@mmcgowanBOS did some quick discovery and determined that "it looks like there is a property "word-break" that is causing that to happen. See screenshot."

![Screen Shot 2019-03-28 at 12 22 47 PM](https://user-images.githubusercontent.com/20731897/55185604-152afc80-516b-11e9-9f2d-e272bd07bfc5.png)

putting in as a ticket for next bash week to look through and determine what might be going on and then fix for D8.

**Comment by fionawhim** [comment]
All set. (You may need to hard reload to get the latest CSS)

<img width="425" alt="Screen Shot 2019-05-22 at 10 16 17 AM" src="https://user-images.githubusercontent.com/260837/58181947-b4a3d180-7c7a-11e9-9268-6b3e3db83fdd.png">
