### ISSUE TITLE
Cityscore page mobile view

### ISSUE THREAD

**Issue by mmcgowanBOS** [CityOfBoston/boston.gov-d7#1323]
#### Expected Behavior/Acceptance Criteria 
<br>
Table TR extends to full width on mobile views / breakpoint.
#### Actual Behavior
<br>
Table TR is only stretching to about half of the screen / container.

#### Browser
<br> 

#### Device
<br> 

#### Example URL
<br> 

#### Relevant Screenshot(s) or Logs
<br> 

#### Steps to Reproduce the Behavior/How to Test
<br> 

_Reminder: Add any relevant Labels, Projects, and/or Milestone(s). If fields don't apply, please right N/A._

**Comment by mmcgowanBOS** [comment]
![Screen Shot 2019-04-03 at 2 02 31 PM](https://user-images.githubusercontent.com/44584567/55502024-adb4f700-5619-11e9-985a-b0db8fbf8ecb.png)

**Comment by reillyzlab** [comment]
Closing since we're moving to Drupal 8
