### ISSUE TITLE
SAML Permissions for Site Admins on Hub

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d7#1336]
#### Expected Behavior/Acceptance Criteria 
There is a permission called "Change SAML authentication setting for individual accounts" that allows us to connect user accounts to our authentication provider. Currently only the "Administrator" role has this permission, I think we should extend this to "Site Administrator" as well. We set these values manually in this file: `docroot/sites/default/settings/permissions.settings.php`

#### Actual Behavior
When @BrutiAnteneh needs to manually create accounts in the Hub, she as a Site Administrator does not see any settings to enable SAML. This leaves the SAML connection disabled by default which causes issues for all the users created this way because they can't authenticate using their normal Boston password.

#### Browser
All

#### Device
All 

#### Example URL
You can see current permissions here: https://hub.boston.gov/admin/people/permissions

#### Relevant Screenshot(s) or Logs
N/A

#### Steps to Reproduce the Behavior/How to Test
N/A

_Reminder: Add any relevant Labels, Projects, and/or Milestone(s). If fields don't apply, please right N/A._
N/A

@mmcgowanBOS can you take a look at this? Thanks!

**Comment by mmcgowanBOS** [comment]
OK. I've updated the "Change SAML" permission to include role "Site Administrator". See screenshot attached.
![Screen Shot 2019-05-16 at 2 40 21 PM](https://user-images.githubusercontent.com/44584567/57878773-c7388980-77e8-11e9-86b9-b888afcb0b8d.png)

**Comment by mmcgowanBOS** [comment]
@BrutiAnteneh  can you log in and test to make sure things are working for you now?

**Comment by jimafisk** [comment]
Ok great @mmcgowanBOS, I think that's a good short term fix. We should also make a PR to `docroot/sites/default/settings/permissions.settings.php` so this doesn't get blown away on the next deployment. Thanks!

**Comment by BrutiAnteneh** [comment]
Thanks for the quick fix, @jimafisk and @mmcgowanBOS! I just to enabled SAML on an account I'd created earlier today. Nice work!

**Comment by mmcgowanBOS** [comment]
The permissions settings file has now been updated and is deployed on Prod. See PR here #1338

**Comment by BrutiAnteneh** [comment]
@mmcgowanBOS and @jimafisk, making note here that permissions disappeared after a deployment.  Used single sign-on as a workaround.

**Comment by reillyzlab** [comment]
Closing this
