### ISSUE TITLE
Search on boston.gov isn't going to search.boston.gov

### ISSUE THREAD

**Issue by phillipbentonkelly** [CityOfBoston/boston.gov-d7#1393]
#### Expected Behavior/Acceptance Criteria 
Performing a search on Boston.gov should forward you to search.boston.gov (then resolves to boston.gov/search....) 

#### Actual Behavior
you remain on boston.gov and no search results are presented

#### Browser
Google Chrome

#### Device
MacBook Pro 

#### Example URL
https://www.boston.gov/ > goes to > https://www.boston.gov/?utf8=%E2%9C%93&query=traffic

#### Relevant Screenshot(s) or Logs
<img width="1288" alt="Screenshot 2019-11-05 16 15 05" src="https://user-images.githubusercontent.com/2627273/68246770-7c553d00-ffe7-11e9-996d-488ef1311549.png">

#### Steps to Reproduce the Behavior/How to Test
Perform a search on Boston.gov

#### Notes
It looks like the form for the search field is missing the value for the 'action' attribute. Showed it to Jim, he agrees that is the most likely cause.

_Reminder: Add any relevant Labels, Projects, and/or Milestone(s). If fields don't apply, please right N/A._

**Comment by reillyzlab** [comment]
We won't be fixing anything on Drupal 7 that isn't pertinent/broken. 

Closing this here, but link a reference to it here: https://github.com/CityOfBoston/boston.gov-d8/issues/263
