### ISSUE TITLE
Ability to print Web pages

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d7#34]
As a user, I want to view any page on the website and print it out in a printer-friendly format. Usually shows up as a button to click to print.

@matthewcrist prefers to create a printer friendly style sheet, which needs to be done anyway. Instead of a button on pages, Matt thinks we should add a link in the accessibility toolbar on how to print.

More discussion needed on how this will happen and/or may appear on the page. Questions to consider:
- What should the button look like?
- Where should it go on each type of page?
- Should different pages / components be printer-formatted in different ways? Might be a conversation with @matthewcrist about what's possible.

Module references by @hackajesse:
- [Drupal 7 module](https://www.drupal.org/project/entity_print)
- [another Drupal 7 module](https://www.drupal.org/project/print), now deprecated
- [Drupal 8 module](https://www.drupal.org/project/pdf_api)
- Also this: https://www.drupal.org/project/printfriendly

**Comment by wryenmeek** [comment]
**Food for Thought**: Who wants to print? What do they want to Print? and Why do they want to print? What about a browser 'ctrl+p' print doesn't meet user needs? In most cases printing a website to paper is less valuable than browser bookmarking or link sharing. Is this an enhancement because; 'the old site did it' or 'As a user I don't trust digital and print every website' ?

**Comment by StevenBlack** [comment]
Absolutely support printing.  @wryenmeek lots of use cases for printing especially in municipal contexts.  Go to one contentious public meeting, for example, and observe: people print from municipal websites more than many would imagine.

**Comment by StevenBlack** [comment]
This is related to printing, and it's an analogous acid test: make sure the site renders well when used with read-it-later services like Instapaper and Pocket.

I picked a page at random: [AFFIRMATIVE MARKETING](https://www.boston.gov/housing/affirmative-marketing).

Here the body renders just fine but ancillary nice-to-haves don't show; the `Resources` and `Who's Involved` sections don't show. So the Fair Housing and Equity phone number doesn't show in Instapaper or Pocket.

In this case some tweaks to content nesting will solve that.

This is part and parcel with deciding what prints to paper.

**Comment by wryenmeek** [comment]
@StevenBlack I'm not suggesting the site doesn't support printing, just digging into how people are using printed information from the site. Offline Meeting Reference is a great use case, and there are likely _many_ others. Digging into the who, what, and why a bit might reveal some additional insights about what to content to focus on and turn up some related Information Architecture issues that might be better options than a global print button.

The suggested printer-friendly style sheet is a great place to start; it should make printing much cleaner from any browser. Additionally, If there is a way to get some analytics when & where it's used, that would help hone in on what content users are interested in printing most.

**Comment by matthewcrist** [comment]
Not sure this one is completely ready to go. We should discuss this a bit more. My preference is for a print friendly style sheet combined with a print button sidebar component that replicates CMD+P for constituents who are not familiar with browser print functionality.

**Comment by hackajesse** [comment]
@gilronc in #163 discussed a documents landing page. Could be useful to think about how these work together. 

Does anyone have insight into giving the report creator the ability to enter charts / graphs, etc. and then have those nicely printable - similar to what a Word / InDesign --> PDF process might be now?

**Comment by matthewcrist** [comment]
@hackajesse Any charting library we use would be printer friendly. We would just need to make sure that the charts are built responsively.

**Comment by reillyzlab** [comment]
Specifications that we've decided on:

**Goal:** To maintain a good user experience for 'anonymous' users of boston.gov or the Hub when they choose to print any page of the website.

**Acceptance Criteria:**

- Create a print style sheet, which will load when a user prompts the print function on any Web browser.

- The style sheet should print exactly what's on the page with the following exceptions:

_Exclude/ignore the following:_

- [ ] Components:
       Hero image
       Featured guides
       Video
       Photo
- [ ] Header
- [ ] Hamburger menu
- [ ] Secondary navigation menu
- [ ] City seal
- [ ] Overlay on top of hero image/page header (optimistic blue/aqua color and diagonal lines)
- [ ] Superfluous images and icons (that are not in line with text)
- [ ] Footer


_Ensure the following stays/appears:_

- [ ] Logo 
- [ ] Fonts
- [ ] iFrame body content
- [ ] Images that are in line with/relevant to surrounding text


_Will need to make adjustments to include the following:_

- [ ] Good looking margins (play with it while putting the style sheet together)
- [ ] Groups/grids of links that include and display the title, description, _and URL_
- [ ] Making all coloring (including images) black and white 
- [ ] All drawers being open (rather than closed) even if the user hasn't opened them
- [ ] Display of all how to and tabbed content all on the same page rather than broken up into the separate tabs
- [ ] Replacement of the feedback modal to instead be text at the bottom of the page that says: For help with the website, please email feedback@boston.gov. For all other non-emergency requests, contact BOS:311 by calling 311, tweeting @BOS311, or visiting boston.gov/311.

**Success Metrics:** 

- Pages look visually appealing when printed from any browser. 
- Users report having a positive experience printing pages from boston.gov or the Hub.

@matthewcrist @jduffy2001 @hackajesse please review to ensure I captured everything

**Comment by hackajesse** [comment]
@reillyzlab:
We should clarify what "superfluous" / "relevant" images and icons are more specifically. Perhaps remove all icons completely? Images that are contained in intro / body fields or part of specific components (which ones?).
The feedback modal gets converted to text automatically, so that should be removed and replaced w/the copy you specified.

**Comment by jduffy2001** [comment]
Example links for content:

Article pages:
https://www.boston.gov/departments/parking-clerk/how-do-parking-meters-work
https://www.boston.gov/departments/tax-collection/motor-vehicle-and-boat-tax

How-to (easy):
https://www.boston.gov/departments/parking-clerk/how-pay-parking-ticket

How-to (more detailed):
https://www.boston.gov/departments/environment/how-report-your-buildings-energy-use

Program page (easy):
https://www.boston.gov/departments/arts-and-culture/opportunity-fund

Program page (more detailed):
https://www.boston.gov/community-preservation
https://www.boston.gov/departments/environment/climate-ready-boston

**Comment by jimafisk** [comment]
This was fixed by https://github.com/CityOfBoston/patterns/pull/312
